ARG vPython

FROM python:${vPython}

WORKDIR /app

ARG capa

COPY src/capas/python/${capa}/requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt -t /python

RUN apt-get update && apt-get install -y zip

ARG nArchivo
RUN zip -r ${nArchivo}.zip  /python

CMD ["echo", "Python dependencies packaged!"]
